export {default as Landing} from "./Landing"
export {default as Login} from "./Login"
export {default as Signup} from "./Signup"
export {default as Dashboard} from "./Dashboard"
export {default as Quizzes} from "./Quizzes"
export {default as Flashcards} from "./Flashcards"
export {default as Friends} from "./Friends"
export {default as Logout} from "./Logout"