DROP TABLE IF EXISTS quiz;
DROP TABLE IF EXISTS flashcard;
DROP TABLE IF EXISTS score;
DROP TABLE IF EXISTS token;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  user_id INT GENERATED ALWAYS AS IDENTITY,
  username VARCHAR(60) UNIQUE NOT NULL,
  email VARCHAR(120) NOT NULL,
  password VARCHAR(140) NOT NULL,
  score INT DEFAULT 0,
  score_out_of INT DEFAULT 0,
  isAdmin BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (user_id)
);

INSERT INTO users (username, email, password, isAdmin) VALUES ('admin', 'admin@appname.org', 'admin', TRUE);
INSERT INTO users (username, email, password) VALUES ('users', 'users@appname.org', 'users');

CREATE TABLE quiz (
  question_id INT GENERATED ALWAYS AS IDENTITY,
  quiz_id INT NOT NULL,
  subject VARCHAR(100) NOT NULL,
  question VARCHAR(256) NOT NULL,
  answer VARCHAR(256) NOT NULL,
  fake_answer1 VARCHAR(256) NOT NULL,
  fake_answer2 VARCHAR(256) NOT NULL,
  fake_answer3 VARCHAR(256) NOT NULL,
  PRIMARY KEY (question_id)
);

INSERT INTO quiz (quiz_id, subject, question, answer, fake_answer1, fake_answer2, fake_answer3) VALUES (1, 'Geography GCSE', 'What is the process by which rocks are broken down by the action of water, wind, and ice?', 'Weathering', 'Erosion', 'Deposition', 'Uplift'),
(1, 'Geography GCSE', 'What is the term for the line of longitude that is opposite to the Prime Meridian?', 'International Date Line', 'Equator', 'Tropic of Cancer', 'Tropic of Capricorn'),
(1, 'Geography GCSE', 'What is the term for a sudden and violent weather disturbance with strong winds, heavy rain, lightning, and thunder?', 'Thunderstorm', 'Tornado', 'Hurricane', 'Tsunami'),
(1, 'Geography GCSE', 'What is the term for a type of soil that is rich in minerals and nutrients and is often found in tropical rainforests?', 'Laterite', 'Loess', 'Podzol', 'Chernozem'),
(1, 'Geography GCSE', 'What is the term for the movement of people from one place to another?', 'Migration', 'Immigration', 'Emigration', 'Transmigration'),
(1, 'Geography GCSE', 'What is the term for the process by which a physical feature or landscape is made smaller by human activity?', 'Degradation', 'Deforestation', 'Desertification', 'Erosion'),
(1, 'Geography GCSE', 'What is the term for the transfer of heat in the atmosphere by the movement of air?', 'Convection', 'Conduction', 'Radiation', 'Evaporation'),
(1, 'Geography GCSE', 'What is the term for a line on a map that connects points of equal atmospheric pressure?', 'Isobar', 'Isotherm', 'Contour', 'Gradient'),
(1, 'Geography GCSE', 'What is the term for a long, narrow inlet of the sea between steep cliffs?', 'Fjord', 'Estuary', 'Cove', 'Bay'),
(1, 'Geography GCSE', 'What is the term for the process by which soil and rock are removed from the Earth''s surface by natural processes such as wind and water?', 'Erosion', 'Deposition', 'Weathering', 'Uplift'),
(1, 'Geography GCSE', 'What is the name for the layer of gases that surrounds the Earth?', 'Atmosphere', 'Biosphere', 'Hydrosphere', 'Lithosphere'),
(1, 'Geography GCSE', 'What is the term for the point on the Earth''s surface directly above the focus of an earthquake?', 'Epicenter', 'Tectonic Plate', 'Mantle', 'Seismograph'),
(1, 'Geography GCSE', 'What is the term for a type of volcano that is made up of layers of ash and lava?', 'Composite volcano', 'Shield volcano', 'Cinder cone volcano', 'Fissure volcano'),
(1, 'Geography GCSE', 'What is the term for the process by which carbon dioxide is absorbed by plants and converted into organic compounds?', 'Photosynthesis', 'Respiration', 'Decomposition', 'Combustion'),
(1, 'Geography GCSE', 'What is the term for the process by which water changes from a liquid to a gas?', 'Evaporation', 'Condensation', 'Precipitation', 'Transpiration'),
(1, 'Geography GCSE', 'What is the term for the gradual movement of the continents across the Earth''s surface?', 'Continental drift', 'Plate tectonics', 'Seafloor spreading', 'Volcanic activity'),
(1, 'Geography GCSE', 'What is the term for a type of rock that is formed from cooled and solidified lava or magma?', 'Igneous rock', 'Metamorphic rock', 'Sedimentary rock', 'Rock cycle'),
(1, 'Geography GCSE', 'What is the term for a large, rotating storm system with high winds and heavy rain that forms over tropical oceans?', 'Hurricane', 'Tornado', 'Thunderstorm', 'Cyclone'),
(1, 'Geography GCSE', 'What is the term for a body of water that is partially enclosed by land?', 'Sea', 'Lake', 'Bay', 'Delta'),
(1, 'Geography GCSE', 'What is the term for the process by which water in the ground is brought to the surface by natural or artificial means?', 'Groundwater recharge', 'Groundwater discharge', 'Aquifer', 'Permeability'),
(2, 'Geography A-Level', 'What is the term used to describe the phenomenon of the Earth''s atmosphere trapping heat from the sun and warming the planet''s surface?', 'Greenhouse effect', 'Solar radiation', 'Global warming', 'Climate change'),
(2, 'Geography A-Level', 'What is the name of the process by which the ocean''s water circulates, transporting heat and nutrients around the globe?', 'Ocean currents', 'Tidal circulation', 'Wave action', 'Salinity gradient'),
(2, 'Geography A-Level', 'What is the term used to describe the erosion of soil and rock caused by wind or water?', 'Erosion', 'Weathering', 'Mass movement', 'Deposition'),
(2, 'Geography A-Level', 'Which of the following is an example of a tectonic plate boundary where two plates move apart from each other?', 'Divergent boundary', 'Transform boundary', 'Convergent boundary', 'Subduction boundary'),
(2, 'Geography A-Level', 'What is the term used to describe the movement of people from one place to another?', 'Migration', 'Emigration', 'Immigration', 'Urbanization'),
(2, 'Geography A-Level', 'What is the name of the system of ocean currents that flow clockwise in the North Atlantic and counterclockwise in the South Atlantic?', 'Gulf Stream', 'North Atlantic Current', 'Antarctic Circumpolar Current', 'South Equatorial Current'),
(2, 'Geography A-Level', 'Which of the following is an example of a renewable energy source?', 'Solar power', 'Coal', 'Oil', 'Natural gas'),
(2, 'Geography A-Level', 'What is the term used to describe the amount of water vapor present in the Earth''s atmosphere?', 'Humidity', 'Precipitation', 'Evaporation', 'Condensation'),
(2, 'Geography A-Level', 'Which of the following is a characteristic of a tropical rainforest biome?', 'High temperature and high rainfall', 'Low temperature and low rainfall', 'High temperature and low rainfall', 'Low temperature and high rainfall'),
(2, 'Geography A-Level', 'What is the name of the process by which water is removed from the leaves of plants and released into the atmosphere?', 'Transpiration', 'Photosynthesis', 'Respiration', 'Evaporation'),
(3, 'History GCSE', 'What was the name of the British Prime Minister who led the country during World War II?', 'Winston Churchill', 'Neville Chamberlain', 'Clement Attlee', 'Margaret Thatcher'),
(3, 'History GCSE', 'What was the name of the American President who led the country during World War II?', 'Franklin D. Roosevelt', 'Harry S. Truman', 'Dwight D. Eisenhower', 'John F. Kennedy'),
(3, 'History GCSE', 'What was the name of the treaty that ended World War I?', 'Treaty of Versailles', 'Treaty of Brest-Litovsk', 'Treaty of Trianon', 'Treaty of Lausanne'),
(3, 'History GCSE', 'Who was the first Roman Emperor?', 'Augustus', 'Julius Caesar', 'Caligula', 'Nero'),
(3, 'History GCSE', 'What was the name of the period of political and social upheaval in France that began in 1789?', 'French Revolution', 'Industrial Revolution', 'Enlightenment', 'Reformation'),
(3, 'History GCSE', 'Who was the first President of the United States?', 'George Washington', 'Thomas Jefferson', 'John Adams', 'James Madison'),
(3, 'History GCSE', 'What was the name of the British monarch who ruled for over 63 years, from 1837 to 1901?', 'Queen Victoria', 'King Edward VII', 'King George V', 'King William IV'),
(3, 'History GCSE', 'What was the name of the German leader who led the country during World War II?', 'Adolf Hitler', 'Paul von Hindenburg', 'Heinrich Himmler', 'Hermann Göring'),
(3, 'History GCSE', 'What was the name of the American civil rights activist who was assassinated in 1968?', 'Martin Luther King Jr.', 'Malcolm X', 'Rosa Parks', 'Thurgood Marshall'),
(3, 'History GCSE', 'Who was the leader of the Soviet Union during the Cuban Missile Crisis?', 'Nikita Khrushchev', 'Joseph Stalin', 'Mikhail Gorbachev', 'Vladimir Putin'),
(3, 'History GCSE', 'What was the name of the ancient Greek city-state that was known for its military prowess?', 'Sparta', 'Athens', 'Thebes', 'Corinth'),
(3, 'History GCSE', 'What was the name of the famous Roman general who conquered Gaul?', 'Julius Caesar', 'Mark Antony', 'Octavian', 'Pompey'),
(3, 'History GCSE', 'Who was the leader of the United States during the Civil War?', 'Abraham Lincoln', 'Ulysses S. Grant', 'Andrew Johnson', 'James Buchanan'),
(3, 'History GCSE', 'What was the name of the African country that was colonized by Italy in the late 19th century?', 'Ethiopia', 'Liberia', 'Tanzania', 'Zimbabwe'),
(3, 'History GCSE', 'Who was the first female Prime Minister of the United Kingdom?', 'Margaret Thatcher', 'Theresa May', 'Angela Merkel', 'Jacinda Ardern'),
(3, 'History GCSE', 'Who was the leader of the Soviet Union during World War II?', 'Joseph Stalin', 'Vladimir Lenin', 'Nikita Khrushchev', 'Mikhail Gorbachev'),
(3, 'History GCSE', 'What was the name of the battle in 1066 that resulted in the Norman Conquest of England?', 'Battle of Hastings', 'Battle of Stamford Bridge', 'Battle of Bosworth Field', 'Battle of Agincourt'),
(3, 'History GCSE', 'What was the name of the ship that Charles Darwin sailed on during his scientific expedition?', 'HMS Beagle', 'HMS Bounty', 'HMS Endeavour', 'HMS Victory'),
(3, 'History GCSE', 'What was the name of the treaty that ended the American Revolution?', 'Treaty of Paris', 'Treaty of London', 'Treaty of Utrecht', 'Treaty of Ghent'),
(3, 'History GCSE', 'Who was the Egyptian queen who formed an alliance with Mark Antony against Octavian?', 'Cleopatra', 'Nefertiti', 'Hatshepsut', 'Nefertari'),
(4, 'History A-Level', 'What was the name of the major naval battle fought between the British and Spanish fleets in 1588?', 'Battle of the Armada', 'Battle of Trafalgar', 'Battle of Waterloo', 'Battle of Jutland'),
(4, 'History A-Level', 'Who was the Russian mystic who influenced the Russian Royal Family in the early 20th century?', 'Rasputin', 'Stolypin', 'Kerensky', 'Trotsky'),
(4, 'History A-Level', 'What was the name of the peace treaty that ended the Thirty Years War in 1648?', 'Treaty of Westphalia', 'Treaty of Augsburg', 'Treaty of Utrecht', 'Treaty of Vienna'),
(4, 'History A-Level', 'Who was the leader of the Bolsheviks during the Russian Revolution?', 'Vladimir Lenin', 'Joseph Stalin', 'Leon Trotsky', 'Nikolai Bukharin'),
(4, 'History A-Level', 'What was the name of the organization created after World War II to promote international cooperation and prevent another world war?', 'United Nations', 'League of Nations', 'NATO', 'European Union'),
(4, 'History A-Level', 'What was the name of the British Prime Minister who was responsible for decolonization in India?', 'Clement Attlee', 'Winston Churchill', 'Harold Macmillan', 'Anthony Eden'),
(4, 'History A-Level', 'Who was the first female monarch of England?', 'Queen Mary I', 'Queen Elizabeth I', 'Queen Victoria', 'Queen Anne'),
(4, 'History A-Level', 'What was the name of the policy of apartheid in South Africa?', 'Apartheid', 'Separate but Equal', 'Jim Crow', 'Segregation'),
(4, 'History A-Level', 'Who was the German philosopher who wrote "The Communist Manifesto" with Friedrich Engels?', 'Karl Marx', 'Friedrich Nietzsche', 'Jean-Paul Sartre', 'Michel Foucault'),
(4, 'History A-Level', 'What was the name of the event in which King Henry VIII of England broke away from the Roman Catholic Church?', 'English Reformation', 'Great Schism', 'Protestant Reformation', 'Counter-Reformation'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a solid changes directly into a gas without passing through a liquid state?', 'Sublimation', 'Deposition', 'Evaporation', 'Condensation'),
(5, 'Chemistry GCSE', 'What is the name of the process by which two or more substances combine to form a new compound?', 'Synthesis', 'Decomposition', 'Polymerization', 'Combustion'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a chemical reaction is sped up by adding a catalyst?', 'Catalysis', 'Inhibition', 'Equilibrium', 'Activation'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a molecule loses an electron and is oxidized?', 'Oxidation', 'Reduction', 'Electrolysis', 'Polymerization'),
(5, 'Chemistry GCSE', 'What is the name of the process by which an acid reacts with a carbonate to produce a salt, water and carbon dioxide?', 'Acid-base reaction', 'Neutralization', 'Oxidation-reduction', 'Polymerization'),
(5, 'Chemistry GCSE', 'What is the name of the process by which light energy is used to convert carbon dioxide and water into glucose and oxygen?', 'Photosynthesis', 'Respiration', 'Transpiration', 'Evaporation'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a liquid is converted into a solid?', 'Freezing', 'Melting', 'Condensation', 'Sublimation'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a substance reacts with oxygen to produce heat and light?', 'Combustion', 'Polymerization', 'Synthesis', 'Decomposition'),
(5, 'Chemistry GCSE', 'What is the name of the process by which an element gains an electron and is reduced?', 'Reduction', 'Oxidation', 'Electrolysis', 'Polymerization'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a gas is dissolved in a liquid to form a solution?', 'Absorption', 'Adsorption', 'Desorption', 'Distillation'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a liquid turns into a gas at a temperature below its boiling point?', 'Evaporation', 'Sublimation', 'Condensation', 'Melting'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a compound breaks down into two or more simpler substances?', 'Decomposition', 'Synthesis', 'Polymerization', 'Combustion'),
(5, 'Chemistry GCSE', 'What is the name of the process by which the concentration of a solution is decreased by adding more solvent?', 'Dilution', 'Concentration', 'Neutralization', 'Oxidation-reduction'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a substance absorbs water and swells up?', 'Hydration', 'Dehydration', 'Condensation', 'Sublimation'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a gas changes into a liquid?', 'Condensation', 'Evaporation', 'Sublimation', 'Melting'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a reaction occurs without any external influence?', 'Spontaneous reaction', 'Catalyzed reaction', 'Inhibited reaction', 'Activated reaction'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a substance is broken down by an electric current?', 'Electrolysis', 'Redox reaction', 'Polymerization', 'Neutralization'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a substance changes from a liquid to a gas?', 'Vaporization', 'Condensation', 'Sublimation', 'Melting'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a gas is passed through a liquid to remove impurities?', 'Scrubbing', 'Distillation', 'Filtration', 'Chromatography'),
(5, 'Chemistry GCSE', 'What is the name of the process by which a substance gains water molecules from its surroundings?', 'Hygroscopy', 'Desiccation', 'Oxidation', 'Reduction'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a molecule absorbs light energy and transitions to a higher electronic energy state?', 'Electronic Excitation', 'Photoelectron Emission', 'Electronic Relaxation', 'Photoionization'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a chemical reaction occurs with the absorption of heat from the surroundings?', 'Endothermic Reaction', 'Exothermic Reaction', 'Isomerization', 'Polymerization'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a reaction reaches a state in which the rate of the forward reaction is equal to the rate of the reverse reaction?', 'Dynamic Equilibrium', 'Chemical Equilibrium', 'Static Equilibrium', 'Thermodynamic Equilibrium'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a gas is compressed and cooled to form a liquid?', 'Compression Refrigeration', 'Absorption Refrigeration', 'Radiant Cooling', 'Thermoacoustic Cooling'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a molecule is split into two or more fragments, each with a net electronic charge?', 'Ionization', 'Dissociation', 'Hydration', 'Redox Reaction'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a reaction occurs with the release of heat to the surroundings?', 'Exothermic Reaction', 'Endothermic Reaction', 'Polymerization', 'Isomerization'),
(6, 'Chemistry A-Level', 'What is the name of the process by which two or more atomic nuclei are combined to form a heavier nucleus with the release of energy?', 'Nuclear Fusion', 'Nuclear Fission', 'Radioactive Decay', 'Beta Decay'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a molecule or atom loses an electron and is therefore oxidized?', 'Oxidation', 'Reduction', 'Electrolysis', 'Polymerization'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a molecule is attracted to a surface and adheres to it?', 'Adsorption', 'Absorption', 'Desorption', 'Distillation'),
(6, 'Chemistry A-Level', 'What is the name of the process by which a reaction rate increases due to an increase in the concentration of one of the reactants?', 'Rate Law', 'Reaction Order', 'Catalysis', 'Collision Theory'),
(7, 'Biology GCSE', 'What is the process by which cells break down glucose to release energy?', 'Cellular Respiration', 'Photosynthesis', 'Glycolysis', 'Fermentation'),
(7, 'Biology GCSE', 'What is the process by which plants take in carbon dioxide and release oxygen?', 'Photosynthesis', 'Cellular Respiration', 'Transpiration', 'Fermentation'),
(7, 'Biology GCSE', 'What is the term for the basic unit of life?', 'Cell', 'Tissue', 'Organ', 'Organ System'),
(7, 'Biology GCSE', 'What is the name of the process by which cells divide into two identical daughter cells?', 'Mitosis', 'Meiosis', 'Interphase', 'Cytokinesis'),
(7, 'Biology GCSE', 'What is the term for the process by which an organism changes over time in response to changes in its environment?', 'Adaptation', 'Evolution', 'Natural Selection', 'Mutation'),
(7, 'Biology GCSE', 'What is the term for the process by which organisms produce offspring that inherit traits from their parents?', 'Reproduction', 'Meiosis', 'Mitosis', 'Fertilization'),
(7, 'Biology GCSE', 'What is the term for the process by which green plants and algae convert light energy into chemical energy?', 'Photosynthesis', 'Cellular Respiration', 'Transpiration', 'Fermentation'),
(7, 'Biology GCSE', 'What is the term for the protective layer that surrounds the cell and regulates the substances that enter and exit the cell?', 'Cell Membrane', 'Nucleus', 'Cytoplasm', 'Cell Wall'),
(7, 'Biology GCSE', 'What is the term for the network of protein fibers that provide shape and support for a cell?', 'Cytoskeleton', 'Mitochondria', 'Endoplasmic Reticulum', 'Golgi Apparatus'),
(7, 'Biology GCSE', 'What is the term for the process by which genetic information is copied from DNA to RNA?', 'Transcription', 'Translation', 'Replication', 'Transformation'),
(7, 'Biology GCSE', 'What is the name of the process by which blood moves from the heart to the lungs and back again?', 'Pulmonary Circulation', 'Systemic Circulation', 'Coronary Circulation', 'Renal Circulation'),
(7, 'Biology GCSE', 'What is the term for the process by which white blood cells engulf and destroy pathogens?', 'Phagocytosis', 'Pinocytosis', 'Exocytosis', 'Endocytosis'),
(7, 'Biology GCSE', 'What is the term for the specific location of a gene on a chromosome?', 'Locus', 'Allele', 'Genotype', 'Phenotype'),
(7, 'Biology GCSE', 'What is the name of the process by which a nerve impulse travels down a neuron?', 'Action Potential', 'Neurotransmission', 'Synaptic Transmission', 'Axonal Transport'),
(7, 'Biology GCSE', 'What is the term for the process by which two organisms of different species benefit from each other?', 'Mutualism', 'Commensalism', 'Parasitism', 'Predation'),
(7, 'Biology GCSE', 'What is the term for the process by which bacteria exchange genetic material?', 'Conjugation', 'Transformation', 'Transduction', 'Replication'),
(7, 'Biology GCSE', 'What is the term for the movement of water from an area of high concentration to an area of low concentration through a selectively permeable membrane?', 'Osmosis', 'Diffusion', 'Active Transport', 'Facilitated Transport'),
(7, 'Biology GCSE', 'What is the term for the type of bond that holds complementary base pairs together in a DNA molecule?', 'Hydrogen Bond', 'Covalent Bond', 'Ionic Bond', 'Polar Bond'),
(7, 'Biology GCSE', 'What is the term for the process by which DNA is copied during cell division?', 'Replication', 'Transcription', 'Translation', 'Transformation'),
(7, 'Biology GCSE', 'What is the term for the process by which cells become specialized for specific functions?', 'Differentiation', 'Proliferation', 'Apoptosis', 'Metastasis'),
(8, 'Biology A-Level', 'What is the term for the process by which cells engulf and destroy their own organelles?', 'Autophagy', 'Endocytosis', 'Exocytosis', 'Phagocytosis'),
(8, 'Biology A-Level', 'What is the term for the network of protein fibers that organize and move chromosomes during cell division?', 'Spindle Apparatus', 'Cytoskeleton', 'Golgi Complex', 'Lysosome'),
(8, 'Biology A-Level', 'What is the name of the process by which proteins are broken down into smaller polypeptides and amino acids?', 'Proteolysis', 'Protein Synthesis', 'Protein Folding', 'Protein Modification'),
(8, 'Biology A-Level', 'What is the term for the process by which a cell forms two identical daughter cells?', 'Mitosis', 'Meiosis', 'Binary Fission', 'Cytokinesis'),
(8, 'Biology A-Level', 'What is the term for the theory that mitochondria and chloroplasts were originally independent prokaryotic organisms that were engulfed by other cells?', 'Endosymbiotic Theory', 'Cell Theory', 'Germ Theory', 'Evolution Theory'),
(8, 'Biology A-Level', 'What is the term for the process by which RNA is synthesized from a DNA template?', 'Transcription', 'Translation', 'Replication', 'Reverse Transcription'),
(8, 'Biology A-Level', 'What is the term for the genetic makeup of an individual?', 'Genotype', 'Phenotype', 'Allele', 'Locus'),
(8, 'Biology A-Level', 'What is the name of the structure that connects the two halves of the brain?', 'Corpus Callosum', 'Medulla Oblongata', 'Hippocampus', 'Thalamus'),
(8, 'Biology A-Level', 'What is the term for the process by which cells convert glucose into ATP in the presence of oxygen?', 'Cellular Respiration', 'Glycolysis', 'Fermentation', 'Anaerobic Respiration'),
(8, 'Biology A-Level', 'What is the term for the process by which a group of cells becomes structurally and functionally specialized?', 'Morphogenesis', 'Differentiation', 'Organogenesis', 'Apoptosis'),
(9, 'Physics GCSE', 'What is the term for the force that opposes motion between two surfaces that are in contact?', 'Friction', 'Gravity', 'Momentum', 'Acceleration'),
(9, 'Physics GCSE', 'What is the unit of measurement for force?', 'Newton', 'Watt', 'Joule', 'Meter'),
(9, 'Physics GCSE', 'What is the term for the force that opposes motion through a fluid?', 'Drag', 'Lift', 'Buoyancy', 'Thrust'),
(9, 'Physics GCSE', 'What is the term for the tendency of an object to resist changes in its state of motion?', 'Inertia', 'Momentum', 'Acceleration', 'Force'),
(9, 'Physics GCSE', 'What is the term for the force that pulls objects towards each other?', 'Gravity', 'Electromagnetism', 'Strong Nuclear Force', 'Weak Nuclear Force'),
(9, 'Physics GCSE', 'What is the term for the energy possessed by a body due to its motion?', 'Kinetic Energy', 'Potential Energy', 'Thermal Energy', 'Electrical Energy'),
(9, 'Physics GCSE', 'What is the term for the energy stored in an object due to its position or configuration?', 'Potential Energy', 'Kinetic Energy', 'Thermal Energy', 'Electrical Energy'),
(9, 'Physics GCSE', 'What is the term for the force that causes an object to move in a circular path?', 'Centripetal Force', 'Gravitational Force', 'Magnetic Force', 'Electric Force'),
(9, 'Physics GCSE', 'What is the term for the resistance of a fluid to flow?', 'Viscosity', 'Elasticity', 'Plasticity', 'Density'),
(9, 'Physics GCSE', 'What is the term for the energy required to raise the temperature of 1 gram of water by 1 degree Celsius?', 'Specific Heat Capacity', 'Latent Heat', 'Heat of Fusion', 'Heat of Vaporization'),
(9, 'Physics GCSE', 'What is the term for the product of an object''s mass and its velocity?', 'Momentum', 'Kinetic Energy', 'Potential Energy', 'Force'),
(9, 'Physics GCSE', 'What is the term for the change in an object''s velocity over time?', 'Acceleration', 'Speed', 'Velocity', 'Force'),
(9, 'Physics GCSE', 'What is the term for the point in an object where its entire mass can be considered to be concentrated?', 'Centre of Mass', 'Centre of Gravity', 'Centre of Inertia', 'Centre of Rotation'),
(9, 'Physics GCSE', 'What is the term for the measure of the amount of matter in an object?', 'Mass', 'Weight', 'Density', 'Volume'),
(9, 'Physics GCSE', 'What is the term for the force experienced by a charged particle moving in a magnetic field?', 'Lorentz Force', 'Coulomb Force', 'Gravitational Force', 'Electromotive Force'),
(9, 'Physics GCSE', 'What is the term for the ability of an object to do work?', 'Energy', 'Power', 'Force', 'Momentum'),
(9, 'Physics GCSE', 'What is the term for the energy required to change the phase of a substance?', 'Latent Heat', 'Specific Heat Capacity', 'Heat of Fusion', 'Heat of Vaporization'),
(9, 'Physics GCSE', 'What is the term for the process by which thermal energy is transferred through a material?', 'Conduction', 'Convection', 'Radiation', 'Diffusion'),
(9, 'Physics GCSE', 'What is the term for the angle of incidence at which light is refracted at 90 degrees?', 'Critical Angle', 'Angle of Incidence', 'Angle of Reflection', 'Angle of Refraction'),
(9, 'Physics GCSE', 'What is the term for the force exerted by a spring when it is stretched or compressed?', 'Spring Force', 'Tension Force', 'Friction Force', 'Gravity Force'),
(10, 'Physics A-Level', 'What is the term for the phenomenon where a wave changes direction as it passes through an aperture or around an obstacle?', 'Diffraction', 'Refraction', 'Reflection', 'Interference'),
(10, 'Physics A-Level', 'What is the term for the point in an orbit around a planet where an object experiences the greatest gravitational force?', 'Perigee', 'Apoapsis', 'Perihelion', 'Aphelion'),
(10, 'Physics A-Level', 'What is the term for the minimum amount of energy required for a chemical reaction to occur?', 'Activation Energy', 'Binding Energy', 'Ionization Energy', 'Excitation Energy'),
(10, 'Physics A-Level', 'What is the term for the flow of electric charge through a material?', 'Electric Current', 'Voltage', 'Resistance', 'Power'),
(10, 'Physics A-Level', 'What is the term for the property of a material that describes the relationship between the electric field strength and the induced electric polarization in the material?', 'Permittivity', 'Permeability', 'Susceptibility', 'Conductivity'),
(10, 'Physics A-Level', 'What is the term for the theory that explains the behavior of matter at the atomic and subatomic level?', 'Quantum Mechanics', 'Special Relativity', 'General Relativity', 'Classical Mechanics'),
(10, 'Physics A-Level', 'What is the term for the process by which a nucleus splits into two or more smaller nuclei and releases energy?', 'Nuclear Fission', 'Nuclear Fusion', 'Radioactive Decay', 'Neutron Capture'),
(10, 'Physics A-Level', 'What is the term for the temperature at which a material changes from a solid to a liquid?', 'Melting Point', 'Freezing Point', 'Boiling Point', 'Condensation Point'),
(10, 'Physics A-Level', 'What is the term for the phenomenon where a changing magnetic field induces an electric current in a conductor?', 'Electromagnetic Induction', 'Electromagnetic Radiation', 'Electromagnetic Field', 'Electromotive Force'),
(10, 'Physics A-Level', 'What is the term for the property of a material that describes its tendency to resist changes in its motion?', 'Inertia', 'Momentum', 'Friction', 'Acceleration'),
(11, 'Maths GCSE', 'What is the term for a ratio of two numbers expressed as a percentage?', 'Percentage', 'Fraction', 'Decimal', 'Ratio'),
(11, 'Maths GCSE', 'What is the term for the branch of mathematics concerned with the study of shapes, sizes, and positions of objects?', 'Geometry', 'Algebra', 'Trigonometry', 'Calculus'),
(11, 'Maths GCSE', 'What is the term for the average of a set of numbers?', 'Mean', 'Median', 'Mode', 'Range'),
(11, 'Maths GCSE', 'What is the term for the mathematical operation that involves repeated addition?', 'Multiplication', 'Addition', 'Subtraction', 'Division'),
(11, 'Maths GCSE', 'What is the term for the distance around the edge of a circle?', 'Circumference', 'Diameter', 'Radius', 'Area'),
(11, 'Maths GCSE', 'What is the term for the measurement of the steepness or slope of a line?', 'Gradient', 'Intercept', 'Equation', 'Coordinate'),
(11, 'Maths GCSE', 'What is the term for the study of the relationships between the sides and angles of triangles?', 'Trigonometry', 'Geometry', 'Calculus', 'Algebra'),
(11, 'Maths GCSE', 'What is the term for the value of a variable that produces the same output as the input of a function?', 'Inverse', 'Direct', 'Proportional', 'Exponential'),
(11, 'Maths GCSE', 'What is the term for the change in the output of a function caused by a small change in the input?', 'Sensitivity', 'Slope', 'Derivative', 'Integration'),
(11, 'Maths GCSE', 'What is the term for a set of ordered pairs of numbers that can be used to represent a relationship?', 'Graph', 'Function', 'Equation', 'Matrix'),
(11, 'Maths GCSE', 'What is the equation for calculating the area of a rectangle?', 'A = l x w', 'A = l + w', 'A = l/w', 'A = l - w'),
(11, 'Maths GCSE', 'What is the equation for calculating the perimeter of a rectangle?', 'P = 2l + 2w', 'P = lw', 'P = 2(l + w)', 'P = l + w'),
(11, 'Maths GCSE', 'What is the equation for calculating the volume of a cube?', 'V = s³', 'V = s²', 'V = 2s³', 'V = 3s²'),
(11, 'Maths GCSE', 'What is the equation for the Pythagorean theorem?', 'a² + b² = c²', 'a + b = c', 'a/b = c/d', 'a - b = c'),
(11, 'Maths GCSE', 'What is the equation for the slope of a line?', 'm = (y₂ - y₁) / (x₂ - x₁)', 'm = (y₁ - y₂) / (x₁ - x₂)', 'm = (x₂ - x₁) / (y₂ - y₁)', 'm = (x₁ - x₂) / (y₁ - y₂)'),
(11, 'Maths GCSE', 'What is the equation for the quadratic formula?', 'x = (-b ± sqrt(b² - 4ac)) / 2a', 'x = -b / 2a', 'x = -b ± sqrt(b² + 4ac) / 2a', 'x = sqrt(b² - 4ac) / 2a'),
(11, 'Maths GCSE', 'What is the equation for calculating the circumference of a circle?', 'C = 2πr', 'C = πr²', 'C = π/2r', 'C = πr/2'),
(11, 'Maths GCSE', 'What is the equation for calculating the area of a circle?', 'A = πr²', 'A = 2πr', 'A = πr', 'A = 2πr²'),
(11, 'Maths GCSE', 'What is the equation for calculating the slope-intercept form of a linear equation?', 'y = mx + b', 'y = bx + m', 'y = m/bx', 'y = b/mx'),
(11, 'Maths GCSE', 'What is the equation for calculating the midpoint between two points?', '((x₁ + x₂)/2 , (y₁ + y₂)/2)', '(x₁ + y₁, x₂ + y₂)', '(x₁y₂ + x₂y₁, x₁x₂ + y₁y₂)', '(x₁ + x₂, y₁ + y₂)'),
(12, 'Maths A-Level', 'What is the equation for calculating the distance between two points in a 3D space?', 'd = sqrt((x2 - x1)^2 + (y2 - y1)^2 + (z2 - z1)^2)', 'd = sqrt((x2 + x1)^2 + (y2 + y1)^2 + (z2 + z1)^2)', 'd = sqrt((x2 - x1)^2 - (y2 - y1)^2 - (z2 - z1)^2)', 'd = sqrt((x2 + x1)^2 - (y2 + y1)^2 - (z2 + z1)^2)'),
(12, 'Maths A-Level', 'What is the equation for finding the gradient of a curve at a particular point?', 'dy/dx', 'd^2y/dx^2', 'd^3y/dx^3', 'd^4y/dx^4'),
(12, 'Maths A-Level', 'What is the equation for calculating the area of a sector of a circle?', 'A = (θ/360) x πr^2', 'A = θr', 'A = πr^2', 'A = (θ/180) x πr^2'),
(12, 'Maths A-Level', 'What is the equation for finding the integral of a function?', '∫f(x)dx', '∂f(x)/∂x', '∇f(x)', '∑f(x)'),
(12, 'Maths A-Level', 'What is the equation for finding the nth root of a number?', '√(x^(1/n))', '√(x^n)', 'x^(1/n)', 'x^n'),
(12, 'Maths A-Level', 'What is the equation for calculating the standard deviation of a set of data?', 'σ = sqrt(Σ(x - μ)^2/n)', 'σ = Σ(x - μ)^2/n', 'σ = sqrt(Σ(x - μ)/n)', 'σ = Σ(x - μ)/n'),
(12, 'Maths A-Level', 'What is the equation for finding the limit of a function as x approaches a particular value?', 'lim_(x->a) f(x)', 'lim_(x->∞) f(x)', 'lim_(x->0) f(x)', 'lim_(x->-∞) f(x)'),
(12, 'Maths A-Level', 'What is the equation for calculating the magnitude of a vector in 3D space?', '|v| = sqrt(v1^2 + v2^2 + v3^2)', '|v| = v1 + v2 + v3', '|v| = v1 - v2 - v3', '|v| = v1 x v2 x v3'),
(12, 'Maths A-Level', 'What is the equation for finding the roots of a quadratic equation?', '(-b ± sqrt(b^2 - 4ac))/2a', '(-b - sqrt(b^2 - 4ac))/2a', '(-b ± sqrt(b^2 + 4ac))/2a', '(-b - sqrt(b^2 + 4ac))/2a'),
(12, 'Maths A-Level', 'What is the equation for calculating the sum of an infinite geometric series?', 'S = a/(1-r)', 'S = a(1-r)', 'S = a + r', 'S = a/r'),
(13, 'English Lit GCSE', 'Who is the author of the novel "To Kill a Mockingbird"?', 'Harper Lee', 'J.D. Salinger', 'Ernest Hemingway', 'F. Scott Fitzgerald'),
(13, 'English Lit GCSE', 'What is the name of the main character in George Orwell''s "1984"?', 'Winston Smith', 'John Proctor', 'Holden Caulfield', 'Jay Gatsby'),
(13, 'English Lit GCSE', 'What is the name of the protagonist in Charlotte Bronte''s "Jane Eyre"?', 'Jane Eyre', 'Elizabeth Bennet', 'Catherine Earnshaw', 'Marianne Dashwood'),
(13, 'English Lit GCSE', 'What is the name of the character who is a symbol for the "American Dream" in F. Scott Fitzgerald''s "The Great Gatsby"?', 'Jay Gatsby', 'Nick Carraway', 'Daisy Buchanan', 'Tom Buchanan'),
(13, 'English Lit GCSE', 'What is the title of the Shakespearean play in which the character Macbeth appears?', 'Macbeth', 'Hamlet', 'King Lear', 'Romeo and Juliet'),
(13, 'English Lit GCSE', 'Who is the author of the poem "The Waste Land"?', 'T.S. Eliot', 'W.B. Yeats', 'William Shakespeare', 'John Keats'),
(13, 'English Lit GCSE', 'What is the title of the novel by Mary Shelley that features the character Victor Frankenstein and his creation?', 'Frankenstein', 'Dracula', 'The Strange Case of Dr. Jekyll and Mr. Hyde', 'The Picture of Dorian Gray'),
(13, 'English Lit GCSE', 'What is the name of the fictional town in which the events of Harper Lee''s "To Kill a Mockingbird" take place?', 'Maycomb', 'Macon', 'Monroeville', 'Montgomery'),
(13, 'English Lit GCSE', 'What is the title of the poem by William Wordsworth that begins "I wandered lonely as a cloud"?', 'Daffodils', 'Ode to a Nightingale', 'The Waste Land', 'The Love Song of J. Alfred Prufrock'),
(13, 'English Lit GCSE', 'What is the name of the character in William Golding''s "Lord of the Flies" who becomes the leader of the group of boys stranded on the island?', 'Ralph', 'Jack', 'Simon', 'Piggy'),
(13, 'English Lit GCSE', 'Who is the author of the novel "Pride and Prejudice"?', 'Jane Austen', 'Charles Dickens', 'George Eliot', 'Thomas Hardy'),
(13, 'English Lit GCSE', 'What is the name of the character in Emily Bronte''s "Wuthering Heights" who is known for his dark and brooding nature?', 'Heathcliff', 'Mr. Rochester', 'Edward Ferrars', 'Fitzwilliam Darcy'),
(13, 'English Lit GCSE', 'What is the name of the character who is the narrator of Joseph Conrad''s "Heart of Darkness"?', 'Charlie Marlow', 'Kurtz', 'Mr. Kurtz', 'The Manager'),
(13, 'English Lit GCSE', 'What is the title of the play by Oscar Wilde that satirizes the social norms of the Victorian era?', 'The Importance of Being Earnest', 'An Ideal Husband', 'Lady Windermere''s Fan', 'A Woman of No Importance'),
(13, 'English Lit GCSE', 'Who is the author of the play "Hamlet"?', 'William Shakespeare', 'Christopher Marlowe', 'Ben Jonson', 'John Webster'),
(13, 'English Lit GCSE', 'What is the name of the character in Fyodor Dostoevsky''s "Crime and Punishment" who commits murder?', 'Raskolnikov', 'Svidrigailov', 'Porfiry Petrovich', 'Sonya Marmeladova'),
(13, 'English Lit GCSE', 'What is the title of the novel by George Orwell that depicts a totalitarian government and the dangers of totalitarianism?', 'Nineteen Eighty-Four', 'Animal Farm', 'Brave New World', 'Fahrenheit 451'),
(13, 'English Lit GCSE', 'Who is the author of the novel "The Catcher in the Rye"?', 'J.D. Salinger', 'Harper Lee', 'Ernest Hemingway', 'F. Scott Fitzgerald'),
(13, 'English Lit GCSE', 'What is the name of the character in William Shakespeare''s "Hamlet" who is the prince of Denmark?', 'Hamlet', 'Claudius', 'Polonius', 'Laertes'),
(13, 'English Lit GCSE', 'What is the title of the poem by Samuel Taylor Coleridge that begins "In Xanadu did Kubla Khan / A stately pleasure-dome decree"?', 'Kubla Khan', 'The Rime of the Ancient Mariner', 'Ode to a Nightingale', 'The Waste Land'),
(14, 'English Lit A-Level', 'Who is the author of the novel "Middlemarch"?', 'George Eliot', 'Charles Dickens', 'Jane Austen', 'Thomas Hardy'),
(14, 'English Lit A-Level', 'What is the title of the play by Tennessee Williams that features the characters Blanche DuBois and Stanley Kowalski?', 'A Streetcar Named Desire', 'Cat on a Hot Tin Roof', 'The Glass Menagerie', 'Sweet Bird of Youth'),
(14, 'English Lit A-Level', 'What is the name of the character in James Joyce''s "Ulysses" who is the main protagonist?', 'Leopold Bloom', 'Stephen Dedalus', 'Molly Bloom', 'Buck Mulligan'),
(14, 'English Lit A-Level', 'Who is the author of the novel "Mrs. Dalloway"?', 'Virginia Woolf', 'D.H. Lawrence', 'E.M. Forster', 'James Joyce'),
(14, 'English Lit A-Level', 'What is the name of the character in Toni Morrison''s "Beloved" who is a former slave and mother of the main character?', 'Sethe', 'Paul D', 'Denver', 'Baby Suggs'),
(14, 'English Lit A-Level', 'What is the title of the play by Samuel Beckett that features two characters, Vladimir and Estragon, who wait for the arrival of someone named Godot?', 'Waiting for Godot', 'Endgame', 'Krapp''s Last Tape', 'Happy Days'),
(14, 'English Lit A-Level', 'Who is the author of the novel "The Picture of Dorian Gray"?', 'Oscar Wilde', 'Joseph Conrad', 'Henry James', 'Edith Wharton'),
(14, 'English Lit A-Level', 'What is the name of the character in Mary Shelley''s "Frankenstein" who is the scientist who creates the monster?', 'Victor Frankenstein', 'Henry Clerval', 'Robert Walton', 'Alphonse Frankenstein'),
(14, 'English Lit A-Level', 'What is the title of the play by Harold Pinter that features the characters Aston, Mick, and Davies?', 'The Caretaker', 'The Birthday Party', 'Betrayal', 'Old Times'),
(14, 'English Lit A-Level', 'Who is the author of the novel "The Sound and the Fury"?', 'William Faulkner', 'Ernest Hemingway', 'F. Scott Fitzgerald', 'John Steinbeck');

CREATE TABLE flashcard (
  card_id INT GENERATED ALWAYS AS IDENTITY,
  collection VARCHAR(100) NOT NULL,
  question VARCHAR(256) NOT NULL,
  fact VARCHAR(256) NOT NULL,
  user_id INT DEFAULT (1),
  PRIMARY KEY (card_id),
  FOREIGN KEY (user_id) REFERENCES users("user_id")
);

INSERT INTO flashcard (collection, question, fact) VALUES ('Chemistry', 'What is the most abundant element in the Earth''s atmosphere?', 'Nitrogen'), ('Chemistry', 'What is the lightest element?', 'Hydrogen'), ('Chemistry', 'What is the densest naturally occurring element?', 'Osmium'), ('Chemistry', 'What element is the primary component of diamonds?', 'Carbon'), ('Chemistry', 'What element has the symbol Fe?', 'Iron'), ('Chemistry', 'What element is used to make light bulbs?', 'Tungsten'), ('Chemistry', 'What element has the atomic number 79?', 'Gold'), ('Chemistry', 'What element is used to make computer chips?', 'Silicon'), ('Chemistry', 'What element is commonly used as a coolant in nuclear reactors?', 'Helium'), ('Chemistry', 'What element has the atomic number 47?', 'Silver'), ('Chemistry', 'What element is used in thermometers?', 'Mercury'), ('Chemistry', 'What is the rarest naturally occurring element?', 'Astatine'), ('Chemistry', 'What element is used to create purple color in fireworks?', 'Potassium'), ('Chemistry', 'What is the only element that is a liquid at room temperature?', 'Mercury'), ('Chemistry', 'What element is used to create blue color in fireworks?', 'Copper'), ('Chemistry', 'What element is used to create red color in fireworks?', 'Strontium'), ('Chemistry', 'What element is used in batteries?', 'Lithium'), ('Chemistry', 'What is the heaviest element that occurs naturally?', 'Uranium'), ('Chemistry', 'What element is used to make fertilizer?', 'Phosphorus'), ('Chemistry', 'What is the most electronegative element?', 'Fluorine'), ('Geography', 'What is the capital of Spain?', 'Madrid'), ('Geography', 'What is the largest country in South America?', 'Brazil'), ('Geography', 'What is the highest mountain in Africa?', 'Mount Kilimanjaro'), ('Geography', 'What is the capital of Japan?', 'Tokyo'), ('Geography', 'What is the longest river in Africa?', 'Nile'), ('Geography', 'What is the smallest country in the world?', 'Vatican City'), ('Geography', 'What is the capital of Italy?', 'Rome'), ('Geography', 'What is the largest desert in the world?', 'Sahara Desert'), ('Geography', 'What is the capital of Egypt?', 'Cairo'), ('Geography', 'What is the largest island in the world?', 'Greenland'), ('Geography', 'What is the highest mountain in the world?', 'Mount Everest'), ('Geography', 'What is the capital of Australia?', 'Canberra'), ('Geography', 'What is the largest ocean in the world?', 'Pacific Ocean'), ('Geography', 'What is the smallest continent?', 'Australia'), ('Geography', 'What is the capital of Russia?', 'Moscow'), ('Geography', 'What is the largest lake in Africa?', 'Lake Victoria'), ('Geography', 'What is the highest peak in North America?', 'Denali/Mount McKinley'), ('Geography', 'What is the longest river in Europe?', 'Volga River'), ('Geography', 'What is the capital of Canada?', 'Ottawa'), ('Geography', 'What is the largest country in the world?', 'Russia'), ('History', 'Who was the first female Prime Minister of the UK?', 'Margaret Thatcher'), ('History', 'Who was the monarch during the Elizabethan era?', 'Queen Elizabeth I'), ('History', 'Which British monarch was known as the ''Virgin Queen''?', 'Queen Elizabeth I'), ('History', 'Who was the leader of the Labour Party during WWII?', 'Clement Attlee'), ('History', 'What event in 1066 is known as the last successful invasion of England?', 'The Norman Conquest'), ('History', 'What was the name of the ship that transported the Pilgrims to the New World in 1620?', 'Mayflower'), ('History', 'Which king was beheaded during the English Civil War?', 'King Charles I'), ('History', 'What was the name of the first successful steam locomotive, invented by George Stephenson?', 'The Rocket'), ('History', 'What was the name of the first British female physician, who practiced medicine in the 19th century?', 'Elizabeth Garrett Anderson'), ('History', 'What was the name of the first woman to be elected to the UK Parliament?', 'Constance Markievicz'), ('History', 'What was the name of the war fought between England and France from 1337 to 1453?', 'The Hundred Years'' War'), ('History', 'Who was the king of England during the Battle of Hastings?', 'Harold II'), ('History', 'What was the name of the infamous prison in London that was in use from the 12th century until 1952?', 'The Tower of London'), ('History', 'Who was the leader of the suffragette movement in the early 20th century?', 'Emmeline Pankhurst'), ('History', 'What was the name of the British passenger liner that sank in the North Atlantic Ocean in 1912?', 'The Titanic'), ('History', 'Which British monarch was known as the ''Merry Monarch''?', 'King Charles II'), ('History', 'Who was the leader of the UK during World War II?', 'Winston Churchill'), ('History', 'What was the name of the battle fought in 1314 where the Scots defeated the English?', 'The Battle of Bannockburn'), ('History', 'Who was the first British monarch to be publicly crowned in a Christian ceremony?', 'King Æthelstan'), ('History', 'What was the name of the military campaign during World War II where the UK and its allies invaded Nazi-occupied Europe?', 'D-Day'), ('Physics', 'What is the force that opposes motion between two surfaces in contact?', 'Friction'), ('Physics', 'What is the formula for calculating work?', 'Work = Force x Distance'), ('Physics', 'What is the force that causes an object to fall to the ground?', 'Gravity'), ('Physics', 'What is the unit of measurement for frequency?', 'Hertz'), ('Physics', 'What is the law that states that every action has an equal and opposite reaction?', 'Newton''s Third Law of Motion'), ('Physics', 'What is the formula for calculating force?', 'Force = Mass x Acceleration'), ('Physics', 'What is the unit of measurement for power?', 'Watt'), ('Physics', 'What is the force that holds atoms together in a molecule?', 'Chemical Bonding'), ('Physics', 'What is the law that states that the total energy in a system remains constant?', 'Law of Conservation of Energy'), ('Physics', 'What is the unit of measurement for electric current?', 'Ampere'), ('Physics', 'What is the phenomenon where a wave changes direction as it passes through a medium?', 'Refraction'), ('Physics', 'What is the unit of measurement for electric potential difference?', 'Volt'), ('Physics', 'What is the phenomenon where light waves change direction as they pass through an opening?', 'Diffraction'), ('Physics', 'What is the unit of measurement for resistance?', 'Ohm'), ('Physics', 'What is the force that causes a moving object to curve?', 'Centripetal Force'), ('Physics', 'What is the unit of measurement for capacitance?', 'Farad'), ('Physics', 'What is the phenomenon where waves overlap and combine?', 'Interference'), ('Physics', 'What is the unit of measurement for magnetic field strength?', 'Tesla'), ('Physics', 'What is the unit of measurement for frequency?', 'Hertz');

-- CREATE TABLE score (
--   score_id INT GENERATED ALWAYS AS IDENTITY,
--   username VARCHAR (256) NOT NULL,
--   score INT DEFAULT 0,
--   score_out_of INT DEFAULT 0,
--   PRIMARY KEY (score_id),
--   FOREIGN KEY (username) REFERENCES users("username")
-- );

CREATE TABLE token (
  token_id INT GENERATED ALWAYS AS IDENTITY,
  user_id INT NOT NULL,
  token CHAR(36) UNIQUE NOT NULL,
  PRIMARY KEY (token_id),
  FOREIGN KEY (user_id) REFERENCES users("user_id")
)

